import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { getErrorMessage, RulesError } from './errors.js';
import {
  activeProfile,
  readLocal,
  RULE_FILES,
  type ActiveProfile,
  type LoadRulesOptions,
  type ProfileChoice,
} from './load-rules.js';
import {
  PROFILE_MANIFEST,
  listProfiles,
  profilePath,
  readProfileManifest,
  type ProfileLocation,
  type ProfileSource,
} from './profile-files.js';
import type {
  ProfileManifest,
  RuleLevel,
  RuleLevels,
  RuleName,
  SteeringSource,
} from './schemas.js';

export const STEERING_START = '<!-- quarterdeck-steering:start -->';
export const STEERING_END = '<!-- quarterdeck-steering:end -->';
export const STEERING_FILE = 'AGENTS.md';

const LEVEL_NOTES: Record<RuleLevel, string> = {
  0: 'off',
  1: 'warns',
  2: 'enforced; a scoped disable comment that names the rule and gives a reason is allowed',
  3: 'enforced and locked; a disable comment naming it is itself a violation',
};

export interface ProfileKickoff {
  profile: string;
  standards: string;
  steering: string;
}

const readStandard = async (path: string): Promise<string> => {
  try {
    return (await readFile(path, 'utf8')).trim();
  } catch (err) {
    throw new RulesError(path, getErrorMessage(err));
  }
};

export const standardsPaths = (
  location: ProfileLocation,
  manifest: ProfileManifest,
): string[] => manifest.standards.map((path) => profilePath(location, path));

const readStandards = async (
  location: ProfileLocation,
  manifest: ProfileManifest,
): Promise<string> => {
  const docs = await Promise.all(
    standardsPaths(location, manifest).map(readStandard),
  );
  return docs.filter((doc) => doc !== '').join('\n\n');
};

const raisedLevel = (
  below: RuleLevel | undefined,
  repo: RuleLevel,
): RuleLevel => Math.max(below ?? 0, repo) as RuleLevel;

export const effectiveLevels = (
  manifest: ProfileManifest,
  profile: Pick<ActiveProfile, 'levels' | 'repoLevels'>,
): RuleLevels => {
  const machine: RuleLevels = { ...manifest.levels, ...profile.levels };
  const raised = Object.entries(profile.repoLevels).map(([rule, level]) => [
    rule,
    raisedLevel(machine[rule], level),
  ]);
  return { ...machine, ...Object.fromEntries(raised) };
};

const levelLine = ([rule, level]: [string, RuleLevel]): string =>
  `- \`${rule}\`: ${level}, ${LEVEL_NOTES[level]}`;

export const renderSteeringBlock = (
  profile: string,
  levels: RuleLevels,
): string => {
  const entries = Object.entries(levels).toSorted(([a], [b]) =>
    a.localeCompare(b),
  );
  if (entries.length === 0) return '';
  return [
    STEERING_START,
    '',
    '# Enforced here',
    '',
    `Generated by Quarterdeck from the rule levels of the \`${profile}\` profile. Do not edit it by hand: change a level in the profile or in \`rules.local.profile.json\`, then regenerate it. 3 is enforced and locked, 2 is enforced with a scoped disable comment allowed, 1 warns, 0 is off.`,
    '',
    ...entries.map(levelLine),
    '',
    STEERING_END,
  ].join('\n');
};

export const extractBlock = (
  text: string,
  start: string,
  end: string,
): string | undefined => {
  const from = text.indexOf(start);
  if (from === -1) return undefined;
  const to = text.indexOf(end, from + start.length);
  if (to === -1) return undefined;
  return text.slice(from, to + end.length);
};

const steeringFromRepo = async (
  source: SteeringSource | undefined,
  repoDir: string | undefined,
): Promise<string | undefined> => {
  if (source === undefined || repoDir === undefined) return undefined;
  const text = await readLocal(resolve(repoDir, source.file));
  if (text === undefined) return undefined;
  return extractBlock(text, source.start, source.end);
};

export const writeSteeringBlock = (text: string, block: string): string => {
  const current = extractBlock(text, STEERING_START, STEERING_END);
  if (current !== undefined) return text.replace(current, block);
  if (text.trim() === '') return `${block}\n`;
  return `${text.trimEnd()}\n\n${block}\n`;
};

export const profileKickoff = async (
  options: LoadRulesOptions = {},
): Promise<ProfileKickoff> => {
  const profile = await activeProfile(options);
  const manifest = await readProfileManifest(profile);
  const fromRepo = await steeringFromRepo(manifest.steering, options.repoDir);
  return {
    profile: profile.name,
    standards: await readStandards(profile, manifest),
    steering:
      fromRepo ??
      renderSteeringBlock(profile.name, effectiveLevels(manifest, profile)),
  };
};

export const kickoffSection = (kickoff: ProfileKickoff): string => {
  const parts: string[] = [];
  if (kickoff.standards !== '')
    parts.push(
      `# Standards\n\nFrom the \`${kickoff.profile}\` rules profile.\n\n${kickoff.standards}`,
    );
  if (kickoff.steering !== '') parts.push(`# Steering\n\n${kickoff.steering}`);
  return parts.join('\n\n');
};

export const withKickoff = (prompt: string, section: string): string => {
  if (section === '') return prompt;
  return `${prompt.trimEnd()}\n\n${section}`;
};

const PROFILE_LAYER_FILES: readonly RuleName[] = [
  'charter',
  'reviewer',
  'lifecycle',
];

export interface ProfileSummary {
  name: string;
  source: ProfileSource;
  dir: string;
  description: string;
  files: string[];
  levels: RuleLevels;
  setup: boolean;
  error: string | null;
}

const layerFiles = async (location: ProfileLocation): Promise<string[]> => {
  const paths = PROFILE_LAYER_FILES.map((name) =>
    resolve(location.dir, RULE_FILES[name]),
  );
  const present = await Promise.all(
    paths.map(async (path) => (await readLocal(path)) !== undefined),
  );
  return paths.filter((_, index) => present[index]);
};

const repoFiles = (
  manifest: ProfileManifest,
  repoDir: string | undefined,
): string[] => {
  if (repoDir === undefined) return [];
  const files = [manifest.steering?.file, manifest.setup?.levelsFile].filter(
    (file): file is string => file !== undefined,
  );
  return files.map((file) => resolve(repoDir, file));
};

const summarize = async (
  location: ProfileLocation,
  repoDir: string | undefined,
): Promise<ProfileSummary> => {
  const manifestPath = resolve(location.dir, PROFILE_MANIFEST);
  const base = {
    name: location.name,
    source: location.source,
    dir: location.dir,
  };
  try {
    const manifest = await readProfileManifest(location);
    return {
      ...base,
      description: manifest.description,
      files: [
        manifestPath,
        ...standardsPaths(location, manifest),
        ...(await layerFiles(location)),
        ...repoFiles(manifest, repoDir),
      ],
      levels: manifest.levels,
      setup: manifest.setup !== undefined,
      error: null,
    };
  } catch (err) {
    return {
      ...base,
      description: '',
      files: [manifestPath],
      levels: {},
      setup: false,
      error: getErrorMessage(err),
    };
  }
};

export interface ProfilesDescription {
  active: string;
  chosenBy: ProfileChoice;
  levels: RuleLevels;
  profiles: ProfileSummary[];
  error: string | null;
}

export const describeProfiles = async (
  options: LoadRulesOptions = {},
): Promise<ProfilesDescription> => {
  const locations = await listProfiles(options);
  const profiles = await Promise.all(
    locations.map((location) => summarize(location, options.repoDir)),
  );
  try {
    const active = await activeProfile(options);
    return {
      active: active.name,
      chosenBy: active.chosenBy,
      levels: active.levels,
      profiles,
      error: null,
    };
  } catch (err) {
    if (!(err instanceof RulesError)) throw err;
    return {
      active: '',
      chosenBy: 'shipped',
      levels: {},
      profiles,
      error: err.message,
    };
  }
};
